package com.cfc.common.workerid.model;

import java.util.Date;

public class WorkerNode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKER_NODE.ID
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKER_NODE.IP
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKER_NODE.PORT
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    private Short port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKER_NODE.APP_NAME
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKER_NODE.CREATE_TIME
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORKER_NODE.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKER_NODE.ID
     *
     * @return the value of WORKER_NODE.ID
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKER_NODE.ID
     *
     * @param id the value for WORKER_NODE.ID
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKER_NODE.IP
     *
     * @return the value of WORKER_NODE.IP
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKER_NODE.IP
     *
     * @param ip the value for WORKER_NODE.IP
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKER_NODE.PORT
     *
     * @return the value of WORKER_NODE.PORT
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public Short getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKER_NODE.PORT
     *
     * @param port the value for WORKER_NODE.PORT
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public void setPort(Short port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKER_NODE.APP_NAME
     *
     * @return the value of WORKER_NODE.APP_NAME
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKER_NODE.APP_NAME
     *
     * @param appName the value for WORKER_NODE.APP_NAME
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKER_NODE.CREATE_TIME
     *
     * @return the value of WORKER_NODE.CREATE_TIME
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKER_NODE.CREATE_TIME
     *
     * @param createTime the value for WORKER_NODE.CREATE_TIME
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORKER_NODE.UPDATE_TIME
     *
     * @return the value of WORKER_NODE.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORKER_NODE.UPDATE_TIME
     *
     * @param updateTime the value for WORKER_NODE.UPDATE_TIME
     *
     * @mbggenerated Mon Sep 28 15:49:10 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}