package com.cfc.common.workerid.server.dao;

import com.cfc.common.workerid.server.model.WorkerNode;

public interface WorkerNodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKER_NODE
     *
     * @mbggenerated Mon Sep 28 17:03:55 CST 2020
     */
    int insert(WorkerNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKER_NODE
     *
     * @mbggenerated Mon Sep 28 17:03:55 CST 2020
     */
    int insertSelective(WorkerNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKER_NODE
     *
     * @mbggenerated Mon Sep 28 17:03:55 CST 2020
     */
    WorkerNode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKER_NODE
     *
     * @mbggenerated Mon Sep 28 17:03:55 CST 2020
     */
    int updateByPrimaryKeySelective(WorkerNode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORKER_NODE
     *
     * @mbggenerated Mon Sep 28 17:03:55 CST 2020
     */
    int updateByPrimaryKey(WorkerNode record);
}