DROP TABLE IF EXISTS WORKER_NODE;
CREATE TABLE WORKER_NODE
(
ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
IP VARCHAR(16) NOT NULL COMMENT 'ip',
PORT SMALLINT(5) UNSIGNED NOT NULL COMMENT 'port',
APP_NAME VARCHAR(32) NOT NULL COMMENT 'app name',
CREATE_TIME DATETIME NOT NULL COMMENT 'create time',
UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
PRIMARY KEY(ID)
)
COMMENT='WorkerID Assigner' ENGINE = INNODB DEFAULT CHARSET=utf8;